# Generated by Django 5.1 on 2024-08-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0003_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
